# Site settings
title: Women in Computing Celebration
description: "The 2nd KYCC-WiC Celebration will be held April 10 - 11, 2015 in Lexington, Kentucky."
baseurl: ""
url: "http://kycc-wic.com"

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed # nested|expanded|compact|compressed
    sass_dir: css
