# Site settings
title: Women in Computing Celebration
email: your-email@domain.com
description: "KYCC-WIC"
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed # nested|expanded|compact|compressed
    sass_dir: css
